name: TAG
description: Plugin For Orimo
author: NiX3r
website: https://www.facebook.com/NiX3rNiX3r
main: cz.nixdevelopment.tag
version: 1.5.1
commands:
    tag:
        description: all commands are here